[package]
name = "tracklib2"
version = "0.1.0"
authors = ["Dan Larkin <dan@danlarkin.org>"]
edition = "2021"

[dependencies]
crc = "2.1"
leb128 = "0.2"
nom = "7.1"
nom-leb128 = "0.2"
thiserror = "1.0"
term-table = {version = "1.3", optional = true}

[dev-dependencies]
assert_matches = "1.5"
criterion = "0.3"
float-cmp = "0.9"

[features]
inspect = ["term-table"]

[[bench]]
name = "parsing"
harness = false
